[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
uuid = { version = "1.8.0", features = ["v4"] }
